name: 'Cypress'

on:
  pull_request:
    paths-ignore:
      - 'terraform/**'
  push:
    paths-ignore:
      - 'terraform/**'
      - 's3/**'
    
jobs:
  cypress:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
