name: 'Cypress'

on:
  push: 
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows'
jobs:
  cypress:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
