name: 'Cypress'

on:
  push:
    paths-ignore:
      - 'terraform/**'
    
jobs:
  cypress:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true

  wait5Minutes:
    needs: [cypress]
    defaults:
      run: 
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Wait 5 minutes so Invalidate has time to propagate
        run: sleep 300

  runCypress2:
    needs: [cypress, wait5Minutes]
    name: Run Cypress again on running site 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run Cypress
        uses: cypress-io/github-action@v2
        env: 
          CYPRESS_baseUrl: https://ccsportfolio.com
        with:
          browser: chrome
          headless: true
