name: 'Terraform and test'
on: 
  pull_request:
    paths: 
      - 'terraform/**'
jobs: 
  terraformPlanAndApply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Terraform init 
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan 
        run: terraform plan 

      - name: Terraform Apply 
        run: terraform apply -auto-approve

  wait5Minutes:
    defaults:
      run: 
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Wait 5 minutes so terraform has time to finish
        run: sleep 300

  runCypress:
    name: Run Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: run Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true