name: Update S3 Bucket, Invalidate CloudFront Cache, Run Cypress

# See https://dev.to/johnkevinlosito/deploy-static-website-to-s3-using-github-actions-4a0e

on:
  push:
    paths:
      - 's3/**'

jobs:
  
  runCypress:
    name: Run Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true

  deployS3AndInvalidateCloudfront:
    needs: runCypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy updated files in "s3" folder to bucket
        run: aws s3 sync ./s3/ s3://ccsportfolio.com --delete

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id E307OQSSKM01JQ --paths "/*"

  wait5Minutes:
    needs: [runCypress, deployS3AndInvalidateCloudfront]
    defaults:
      run: 
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Wait 5 minutes so Invalidate has time to propagate
        run: sleep 300

  runCypress2:
    needs: [runCypress, deployS3AndInvalidateCloudfront, wait5Minutes]
    name: Run Cypress again on running site 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run Cypress
        uses: cypress-io/github-action@v2
        env: 
          CYPRESS_baseUrl: https://ccsportfolio.com
        with:
          browser: chrome
          headless: true